export enum DetailedMuscleGroup {
  BICEPS = 'biceps',
  TRICEPS = 'triceps',
  FOREARMS = 'forearms',
  FRONT_DELTS = 'front_delts',
  SIDE_DELTS = 'side_delts',
  REAR_DELTS = 'rear_delts',
  UPPER_CHEST = 'upper_chest',
  MIDDLE_CHEST = 'middle_chest',
  LOWER_CHEST = 'lower_chest',
  LATS = 'lats',
  RHOMBOIDS = 'rhomboids',
  TRAPS = 'traps',
  LOWER_BACK = 'lower_back',
  UPPER_ABS = 'upper_abs',
  LOWER_ABS = 'lower_abs',
  OBLIQUES = 'obliques',
  GLUTES = 'glutes',
  HIP_FLEXORS = 'hip_flexors',
  ABDUCTORS = 'abductors',
  ADDUCTORS = 'adductors',
  QUADS = 'quads',
  HAMSTRINGS = 'hamstrings',
  CALVES = 'calves',
  NECK = 'neck',
  FULL_BODY = 'full_body',
  CARDIO = 'cardio',
}
